name: General Hourly Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Schedule daily updates
  schedule: [{cron: "*/30 * * * *"}]
jobs:
  master:
    name: Master Tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: TiDB Tests
        uses: ./.github/actions/tidb-tests
        with:
          bazelrc: ${{ secrets.BAZELRC }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          go-version: 1.25
      - name: Run tests
        shell: bash
        run: |
          #!/bin/bash
          git clone https://github.com/pingcap/tidb.git --depth=1 -b master
          cd tidb
          unset CI
          system_name=$(uname -s)
          if [ "$system_name" == "Darwin" ]; then
            sed -i '' '/bazel-cache/d' DEPS.bzl
            sed -i '' '/ats.apps.svc/d' DEPS.bzl
            sed -i '' '/bazel-cache/d' WORKSPACE
            sed -i '' '/ats.apps.svc/d' WORKSPACE
          elif [ "$system_name" == "Linux" ]; then
            sed -i '/bazel-cache/d' DEPS.bzl
            sed -i '/ats.apps.svc/d' DEPS.bzl
            sed -i '/bazel-cache/d' WORKSPACE
            sed -i '/ats.apps.svc/d' WORKSPACE
          fi
          make bazel_bin
          make bazel_prepare

  build:
    name: Master Build Tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Cache bazel output_base
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/bazel-out
          key: bazel-output-${{ runner.os }}-${{ github.workflow }}}-tidb-master-v1
          restore-keys: bazel-output-${{ runner.os }}-${{ github.workflow }}}-
      - name: TiDB Tests
        uses: ./.github/actions/tidb-tests
        with:
          bazelrc: ${{ secrets.BAZELRC }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          go-version: 1.25
      - name: Run tests
        shell: bash
        run: |
          #!/bin/bash
          git clone https://github.com/pingcap/tidb.git --depth=1 -b master
          cd tidb
          unset CI
          system_name=$(uname -s)
          if [ "$system_name" == "Darwin" ]; then
            sed -i '' '/bazel-cache/d' DEPS.bzl
            sed -i '' '/ats.apps.svc/d' DEPS.bzl
            sed -i '' '/bazel-cache/d' WORKSPACE
            sed -i '' '/ats.apps.svc/d' WORKSPACE
          elif [ "$system_name" == "Linux" ]; then
            sed -i '/bazel-cache/d' DEPS.bzl
            sed -i '/ats.apps.svc/d' DEPS.bzl
            sed -i '/bazel-cache/d' WORKSPACE
            sed -i '/ats.apps.svc/d' WORKSPACE
          fi
          OUTPUT_BASE="${RUNNER_TEMP:-/tmp}/bazel-out"
          mkdir -p "$OUTPUT_BASE"
          bazel  --output_base="$OUTPUT_BASE" build //pkg/planner/core/... --//build:with_nogo_flag=true         
