name: General Hourly Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Schedule daily updates
  schedule: [{cron: "*/30 * * * *"}]
jobs:
  master:
    name: Master Tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: TiDB Tests
        uses: ./.github/actions/tidb-tests
        with:
          bazelrc: ${{ secrets.BAZELRC }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          go-version: 1.25
          tidb_branch: master
