name: General Hourly Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Schedule daily updates
  schedule: [{cron: "*/10 * * * *"}]
jobs:
  master:
    name: Master Hourly Tests on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up bazelisk
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          repository-cache: true
          bazelrc: ${{ secrets.BAZELRC}}
