name: General Hourly Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Schedule daily updates
  schedule: [{cron: "*/30 * * * *"}]
jobs:
  master:
    name: Master Tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: TiDB Tests
        uses: ./.github/actions/tidb-tests
        with:
          bazelrc: ${{ secrets.BAZELRC }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          go-version: 1.25
          tidb_branch: master
      - name: Run tests
        shell: bash
        run: |
          #!/bin/bash
          git clone https://github.com/pingcap/tidb.git --depth=1 -b "${{ inputs.tidb_branch }}"
          cd tidb
          unset CI
          system_name=$(uname -s)
          if [ "$system_name" == "Darwin" ]; then
            sed -i '' '/bazel-cache/d' DEPS.bzl
            sed -i '' '/ats.apps.svc/d' DEPS.bzl
            sed -i '' '/bazel-cache/d' WORKSPACE
            sed -i '' '/ats.apps.svc/d' WORKSPACE
          elif [ "$system_name" == "Linux" ]; then
            sed -i '/bazel-cache/d' DEPS.bzl
            sed -i '/ats.apps.svc/d' DEPS.bzl
            sed -i '/bazel-cache/d' WORKSPACE
            sed -i '/ats.apps.svc/d' WORKSPACE
          fi
          make bazel_bin

  build:
    name: Master Build Tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: TiDB Tests
        uses: ./.github/actions/tidb-tests
        with:
          bazelrc: ${{ secrets.BAZELRC }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          go-version: 1.25
          tidb_branch: master
      - name: Run tests
        env:
          BRANCH: ${{ inputs.tidb_branch }}
        shell: bash
        run: |
          #!/bin/bash
          git clone https://github.com/pingcap/tidb.git --depth=1 -b $BRANCH
          cd tidb
          unset CI
          system_name=$(uname -s)
          if [ "$system_name" == "Darwin" ]; then
            sed -i '' '/bazel-cache/d' DEPS.bzl
            sed -i '' '/ats.apps.svc/d' DEPS.bzl
            sed -i '' '/bazel-cache/d' WORKSPACE
            sed -i '' '/ats.apps.svc/d' WORKSPACE
          elif [ "$system_name" == "Linux" ]; then
            sed -i '/bazel-cache/d' DEPS.bzl
            sed -i '/ats.apps.svc/d' DEPS.bzl
            sed -i '/bazel-cache/d' WORKSPACE
            sed -i '/ats.apps.svc/d' WORKSPACE
          fi
          bazel  build //pkg/planner/... --//build:with_nogo_flag=true
          make bazel_prepare          