name: General Hourly Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Schedule daily updates
  schedule: [{cron: "*/30 * * * *"}]
jobs:
  master:
    name: Master Hourly Tests on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: TiDB Tests
        uses: ./.github/actions/tidb-tests
        with:
          bazelrc: ${{ secrets.BAZELRC }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          go-version: 1.25
          tidb_branch: master
  master-ubuntu:  
    name: Master Hourly Tests on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/arm64/v8
          - linux/amd64
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: TiDB Tests
        uses: ./.github/actions/tidb-tests
        with:
          bazelrc: ${{ secrets.BAZELRC }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          go-version: 1.25
          tidb_branch: master
