name: General Hourly Tests
on:
  push:
    branches:
      - main
  # Schedule daily updates
  schedule: [{cron: "*/5 * * * *"}]
jobs:
  master:
    name: Master Hourly Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up bazelisk
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          bazelrc: ${{ secrets.BAZELRC}}
      - name: init gcp
        run: mkdir -p /Users/runner/.secret && echo '${{ secrets.GCP_SA_KEY}}' > /Users/runner/.secret/gcp-compute-dev-9c677af55a0e.json
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25
      - name: clone tidb
        run: git clone https://github.com/pingcap/tidb.git --depth=1 -b master
      - name: Run tests
        run: ï½œ
          cd tidb && \
          unset CI && \ 
          sed -i '/bazel-cache/d'  DEPS.bzl && \
          sed -i '/ats.apps.svc/d'  DEPS.bzl && \
          sed -i '/bazel-cache/d'  WORKSPACE && \
          sed -i '/ali/d'  WORKSPACE && \
          make bazel_bin